---

# In some cases (no all, apparently, but anyway, see https://github.com/ansible/ansible/issues/16139),
# ansible_host under a local_action becomes localhost and we don't want that. To work around this,
# we set another variable here, outside the local_action.
- set_fact:
    gitpush_host: "{{ ansible_host }}"

- name: Ensure that we can gitpush as the user
  authorized_key:
    user: "{{ gitpush_user }}"
    state: present
    key: "{{ item_key }}"
  with_items: "{{ gitpush_ssh_keys }}"
  loop_control:
    loop_var: item_key

