---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: cisco
  connection: network_cli
  gather_facts: no
  vars:
    gitpush_ssh_keys: []
    gitpush_local_repo_path: network-configs/.git
    gitpush_repo_path: network-configs
    gitpush_workdir_path: /var/tmp/backups
    gitpush_user: vinni.sylvester@gmail.com
    gitpush_additional_params: '--force'
    router_backup_dir: backup 
    git_remote_repo_path: 'https://{{ git_user }}:{{ git_pass }}@github.com/vsylvest/Master-Network-Config.git' 
    git_checkout_location: /tmp/network-configs
  roles:
    - role: ansible-gitpull-deploy

  tasks:
  
    - name: GET DATE
      command: 'date +"%m-%d-%y"'
      register: date
      delegate_to: localhost 
       
    - name: GET TIME
      command: 'date +"%T"'
      register: time
      delegate_to: localhost 

      
    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
      register: config_output


    - name: RENAME BACKUP
      copy:
        src: "{{config_output.backup_path}}"
        dest: "./{{router_backup_dir}}/{{inventory_hostname}}-{{ date.stdout }}-{{ time.stdout }}.config"
      delegate_to: localhost 

    - name: REMOVE NON CONFIG LINES
      lineinfile:
        path: "./{{router_backup_dir}}/{{inventory_hostname}}-{{ date.stdout }}-{{ time.stdout }}.config"
        line: "Building configuration..."
        state: absent
      delegate_to: localhost 

    - name: REMOVE NON CONFIG LINES - REGEXP
      lineinfile:
        path: "./{{router_backup_dir}}/{{inventory_hostname}}-{{ date.stdout }}-{{ time.stdout }}.config"
        regexp: 'Current configuration.*'
        state: absent  
      delegate_to: localhost 

    - set_fact:
        gitpush_host: "{{ ansible_host }}"
      delegate_to: localhost 

    - name: ADD BACKUP TO VERSION CONTROL
      copy:
        src: "./{{router_backup_dir}}/{{inventory_hostname}}-{{ date.stdout }}-{{ time.stdout }}.config" 
        dest: "{{ git_checkout_location }}/Backup-Config/"
      delegate_to: localhost 

    - name: PRINT NAME
      debug:
        msg: "{{inventory_hostname}}-{{ date.stdout }}-{{ time.stdout }}.config" 
      delegate_to: localhost 

    - name: ADD BACKUP TO VERSION CONTROL
      copy:
        src: "./{{router_backup_dir}}/{{inventory_hostname}}-{{ date.stdout }}-{{ time.stdout }}.config" 
        dest: "{{ git_checkout_location }}/Backup-Config/"
      delegate_to: localhost 

    - name: PRINT NAME
      debug:
        msg: "{{inventory_hostname}}-{{ date.stdout }}-{{ time.stdout }}.config" 
      delegate_to: localhost 

- name: Push the contents back up into the remote
  hosts: cisco 
  gather_facts: no
  vars:
    gitpush_ssh_keys: []
    gitpush_local_repo_path: network-configs/.git
    gitpush_repo_path: /tmp/network-configs/.git
    gitpush_workdir_path: /tmp/network-configs
    gitpush_user: ansible
    git_checkout_location: /tmp/network-configs
    git_remote_repo_path: 'https://{{ git_user }}:{{ git_pass }}@github.com/vsylvest/Master-Network-Config.git' 

  roles:
    - role: ansible-gitpush-deploy

- name: Push the contents back up into the remote
  hosts: localhost 
  gather_facts: no
  vars:
    gitpush_ssh_keys: []
    gitpush_local_repo_path: network-configs/.git
    gitpush_repo_path: /tmp/network-configs/.git
    gitpush_workdir_path: /tmp/network-configs
    gitpush_user: ansible
    git_checkout_location: /tmp/network-configs
    git_remote_repo_path: 'https://{{ git_user }}:{{ git_pass }}@github.com/vsylvest/Master-Network-Config.git' 

  tasks:

      
    - name: Commit and Push Config Changes to SCM
      shell: "/tmp/./test.sh"
      delegate_to: localhost 

