---
- name: Push Test Router Changes
  hosts: control
  gather_facts: no
  vars:
    gitpush_ssh_keys: []
    gitpush_local_repo_path: test-configs/.git
    gitpush_repo_path: test-configs
    gitpush_workdir_path: /var/tmp/backups
    gitpush_user: vinni.sylvester@gmail.com
    gitpush_additional_params: '--force'
    router_backup_dir: backup 
    git_remote_repo_path: 'https://{{ git_user }}:{{ git_pass }}@github.com/vsylvest/Test-Network-Config.git' 
    git_checkout_location: /tmp/test-configs
  roles:
    - role: ansible-gitpull-deploy

  tasks:

    - name: ADD BACKUP TO VERSION CONTROL
      copy:
        src: "/tmp/test-configs/rtr3.config" 
        dest: "./{{ router_backup_dir }}"




- name: RESTORE CONFIGURATION from SCM
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:
  
    - name: copy file at root dir of flash
      net_put:
        src: "./{{ router_backup_dir }}/rtr3.config"
        protocol: scp
        dest : flash:/rtr3.config
        
    - name: CONFIG REPLACE
      ios_command:
        commands:
          - config replace flash:{{inventory_hostname}}.config force
