---
- name: PUSH ROUTER CONFIGURATIONS from SCM
  hosts: localhost
  connection: network_cli
  gather_facts: no
  tasks:
  
    - name: Remove old config files
      command: "rm /tmp/rtr*"
      
          
    - name: Download latest test config file
      get_url: 
        url: "https://raw.githubusercontent.com/vsylvest/Test-Network-Config/master/rtr4.config"
        dest: /tmp/rtr4.config
        owner: awx
        group: awx
        mode: 0400
        force: yes


- name: RESTORE CONFIGURATION from SCM
  hosts: test
  connection: network_cli
  gather_facts: no

  tasks:
    - name: gather_ios facts
      ios_facts:
      register: iosfact

    - name: copy file at root dir of flash
      net_put:
        src: /tmp/{{inventory_hostname}}.config
        protocol: scp
        dest : flash:/{{inventory_hostname}}.config

#   - name: copy file at root dir of flash
#     command: "scp /tmp/{{inventory_hostname}}.config  {{inventory_hostname}}:/{{inventory_hostname}}.config"

    - name: CONFIG REPLACE
      ios_command:
        commands:
          - config replace flash:{{inventory_hostname}}.config force