---
- name: Push Test Router Changes
  hosts: control
  gather_facts: no
  vars:
    gitpush_ssh_keys: []
    gitpush_local_repo_path: test-configs/.git
    gitpush_repo_path: test-configs
    gitpush_workdir_path: /var/tmp/backups
    gitpush_user: vinni.sylvester@gmail.com
    gitpush_additional_params: '--force'
    router_backup_dir: backup 
    git_remote_repo_path: 'https://{{ git_user }}:{{ git_pass }}@github.com/vsylvest/Test-Network-Config.git' 
    git_checkout_location: /home/student1/test-configs
  roles:
    - role: ansible-gitpull-deploy

  tasks:
    - name: copy file at root dir of flash
      command: "scp /home/student1/test-configs/rtr3.config  ec2-user@rtr3:/rtr3.config"

- name: RESTORE CONFIGURATION from SCM
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:
    - name: CONFIG REPLACE
      ios_command:
        commands:
          - config replace flash:{{inventory_hostname}}.config force
      register: output
     
