---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: test
  connection: network_cli
  gather_facts: no
  vars:
    gitpush_ssh_keys: []
    gitpush_local_repo_path: test-configs/.git
    gitpush_repo_path: test-configs
    gitpush_workdir_path: /var/tmp/backups
    gitpush_user: vinni.sylvester@gmail.com
    gitpush_additional_params: '--force'
    router_backup_dir: backup 
    git_remote_repo_path: 'https://{{ git_user }}:{{ git_pass }}@github.com/vsylvest/Test-Network-Config.git' 
    git_checkout_location: /tmp/test-configs
  roles:
    - role: ansible-gitpull-deploy
      
- name: RESTORE CONFIGURATION from SCM
  hosts: test
  connection: network_cli
  gather_facts: no

  tasks:
    - name: gather_ios facts
      ios_facts:
      register: iosfact

    - name: copy file at root dir of flash
      net_put:
        src: /tmp/test-configs/{{inventory_hostname}}.config
        protocol: scp
        dest : flash:/{{inventory_hostname}}.config

#   - name: copy file at root dir of flash
#     command: "scp /tmp/{{inventory_hostname}}.config  {{inventory_hostname}}:/{{inventory_hostname}}.config"

    - name: CONFIG REPLACE
      ios_command:
        commands:
          - config replace flash:{{inventory_hostname}}.config force
      register: config_status
      
    - name: Save the status to file
      copy: 
        src: {{ config_status }}
        dest: /tmp/conf_status.log